name: praduation_project
description: A new Flutter project.
version: 1.0.1+1

publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # UI and Animation:
  animated_text_kit: ^4.2.2
  banner_carousel: ^1.2.1
  #! carousel_pro: ^1.0.0
  carousel_slider: ^4.2.1
  liquid_swipe: ^3.0.0
  smooth_page_indicator: ^1.0.1
  zoom_tap_animation: ^1.1.0

  # Image and Media:
  cached_network_image: ^3.2.3
  image_picker: ^0.8.7
  multi_image_picker:
  flutter_svg: ^2.0.5
  lottie: ^2.3.2

  # Authentication and Data Storage:
  cloud_firestore: ^4.4.5
  firebase_auth: ^4.2.10
  firebase_core: ^2.7.1
  firebase_database: ^10.0.16
  firebase_storage: ^11.0.16
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.9

  # State Management and Data Handling:
  freezed: ^2.3.2
  get: ^4.6.5
  get_storage: ^2.1.1
  provider: ^6.0.5
  rxdart: ^0.27.7

  # Utilities and Helpers:
  #! awesome_package: ^0.0.1
  google_fonts: ^4.0.4
  font_awesome_flutter: ^10.4.0
  validators: ^3.0.0
  uuid: ^3.0.7
  permission_handler: ^10.2.0
  intl: ^0.17.0
  logging: ^1.1.1

  # User Interface Enhancement:
  legacy_buttons: ^0.0.1
  favorite_button: ^0.0.4
  animated_theme_switcher: ^2.0.8
  flutter_rating_bar: ^4.0.1
  awesome_notifications: ^0.7.4+1
  flutter_slidable: ^3.0.0

  # Authentication Providers:
  google_sign_in: ^6.0.2
  flutter_facebook_auth: ^5.0.8
  email_auth: ^1.0.0

  # UI Input and Forms:
  otp_text_field: ^1.1.3
  date_time_picker: ^2.1.0

  # Other Dependencies:
  show_loader_dialog: ^0.0.2
  logger: ^1.3.0
  fluttertoast: ^8.2.1
  easy_dynamic_theme: ^2.3.0
  flutter_phoenix: ^1.1.1
  email_otp: ^2.0.1
  url_launcher: ^6.1.11
  flutter_web_browser: ^0.17.1
  flutter_keyboard_visibility: ^5.0.0-nullsafety.0
  connectivity_plus: ^4.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/
    - assets/lottie/
    - assets/logo/
